name: "CI - Matrix draft upload"
on: [push]

jobs:
  create_draft_release:
    runs-on: ubuntu-latest
    outputs:
      draft_id: ${{ steps.create_release.outputs.draft_id }}
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          token: '${{ github.token }}'
          repository: '${{ github.repository }}'
      - name: what repo
        run: |
          echo "REPO: ${{ github.repository }}/${{ steps.checkout.outputs.ref }}/${{ steps.checkout.outputs.commit }}, ${{ steps.checkout.conclusion }}"
      - name: Create release
        id: create_release
        uses: ./
        with:
          file: "./README.md"
          draft: true
          body: "Test release to test the matrix upload with a draft release."
          release_name: "Test draft release using Matrix"


  upload_to_release:
    name: Publish on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: create_draft_release
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make readme unique
        run: |
          cp ./README.md ./README-${{ matrix.os }}.md

      - name: Upload README to release
        uses: ./
        with:
          file: "./README-${{ matrix.os }}.md"
          draft: true
          draft_id: ${{ needs.create_draft_release.outputs.draft_id }}
